// let 3nome = 'teste';
let nome3 = 'teste';
let $nome = 'teste';
let _nome = 'teste';
// let @nome = 'teste';
// let !nome = 'teste';
let Nome = 'teste';
let seuNome = 'teste';
let seu_nome = 'teste';